name: Climalert Backend CI

on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js version 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
        working-directory: BackEnd
      - run: npm run build --if-present
        working-directory: BackEnd
      - run: npm test
        working-directory: BackEnd

