name: Climalert Frontend CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest # recommended for android
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: FrontEnd/ClimAlert1
      - name: run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          working-directory: FrontEnd/ClimAlert1
          #script: ./gradlew connectedAndroidTest
          #script: ./gradlew connectedCheck
          script: ./gradlew test

